ETL Process:

/*To get the data together from all the dataset of years 2000 to 2016, the data is merged into single 
master dataset and named as water_quality. For merging the data select and union query is used.*/

INSERT INTO WATER_QUALITY
SELECT * FROM "2000"
UNION ALL
SELECT * FROM "2001"
UNION ALL
SELECT * FROM "2002"
UNION ALL
SELECT * FROM "2003"
UNION ALL
SELECT * FROM "2004"
UNION ALL
SELECT * FROM "2005"
UNION ALL
SELECT * FROM "2006"
UNION ALL
SELECT * FROM "2007"
UNION ALL
SELECT * FROM "2008"
UNION ALL
SELECT * FROM "2009"
UNION ALL
SELECT * FROM "2010"
UNION ALL
SELECT * FROM "2011"
UNION ALL
SELECT * FROM "2012"
UNION ALL
SELECT * FROM "2013"
UNION ALL
SELECT * FROM "2014"
UNION ALL
SELECT * FROM "2015"
UNION ALL
SELECT * FROM "2016"
UNION ALL
